.github/workflows/ci_cd.yml
=> feat: activate codecov on main branch

doc/source/api/index.rst, doc/source/api/parts_types.rst, src/ansys/sherlock/core/analysis.py, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/sherlock.py, src/ansys/sherlock/core/stackup.py, src/ansys/sherlock/core/types/analysis_types.py, src/ansys/sherlock/core/types/common_types.py, src/ansys/sherlock/core/types/parts_types.py, src/ansys/sherlock/core/types/stackup_types.py, tests/test_parts.py, tests/test_stackup.py
Changed Parts.get_part_location() and Stackup.get_stackup_props() to return custom objects
=> Use classes for returning values to API methods

doc/source/getting_started/installation.rst
=> fix: wrong statement regarding Python versions

pyproject.toml, src/ansys/sherlock/core/analysis.py, src/ansys/sherlock/core/common.py, src/ansys/sherlock/core/errors.py, tests/test_analysis.py, tests/test_common.py, tests/test_stackup.py
Add API to update solder fatigue properties, API to get solder fatigue properties fields, and API to get valid solder materials.
=> Add Solder Fatigue APIs

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/project.py, tests/test_project.py, tests/test_stackup.py
=> Add add_cca API

doc/source/api/analysis.rst, pyproject.toml, src/ansys/sherlock/core/analysis.py, src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/project.py, tests/test_analysis.py
Checklist:
- [y] Run unit tests and make sure they all pass
- [y] Check and fix style errors
- [y] Bench test new/modified APIs by using and modifying the code in the example for the API method
- [y] Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)
- [y] Generate documentation
- [y] Verify the HTML. It gets generated at: <pysherlock>\doc\build\html.
- [y] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> Add partmodeling API

doc/source/getting_started/installation.rst, doc/source/user_guide/index.rst
Checklist:
- [na] Run unit tests and make sure they all pass
- [na] Check and fix style errors
- [na] Bench test new/modified APIs by using and modifying the code in the example for the API method
- [na] Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)
- [na] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> User Guide: corrections in example code

src/ansys/sherlock/core/project.py
=> 741587: Add IMS stackup argument in import_odb_archve

doc/source/api/analysis.rst, doc/source/api/common.rst, doc/source/api/launcher.rst, doc/source/api/layer.rst, doc/source/api/lifecycle.rst, doc/source/api/model.rst, doc/source/api/parts.rst, doc/source/api/parts_types.rst, doc/source/api/project.rst, doc/source/api/stackup.rst, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/types/parts_types.py
Checklist:
N/A Bench test new/modified APIs by using and modifying the code in the example for the API method
N/A Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)
=> Updating Api docs

PULL_REQUEST_TEMPLATE.md, src/ansys/sherlock/core/analysis.py, tests/test_analysis.py
Checklist:
- [na] Bench test new/modified APIs by using and modifying the code in the example for the API method
- [na] Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)
- [na] Verify the HTML. It gets generated at: <pysherlock>\doc\build\html.
- [na] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> Fix solder material

src/ansys/sherlock/core/launcher.py
Checklist:
N/A Check and fix style errors
N/A Bench test new/modified APIs by using and modifying the code in the example for the API method
N/A Add new classes to rst files, located at: <pysherlock>\doc\source\api
=> Fix API documentation

.github/labeler.yml, .github/workflows/label.yml
Checklist:
- n/a Bench test new/modified APIs by using and modifying the code in the example for the API method
- n/a Add new classes to rst files, located at: <pysherlock>\doc\source\api
- n/a Generate documentation
- n/a Verify the HTML. It gets generated at: <pysherlock>\doc\build\html.
=> Fix labeler error

doc/source/api/index.rst, doc/source/api/project_types.rst, src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/project.py, src/ansys/sherlock/core/types/project_types.py, tests/test_project.py
=> New API: updateThermalMaps()

.github/workflows/ci_cd.yml
=> fix: codecov

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/model.py, tests/test_model.py
Checklist:
- [] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> Added export_aedb.

doc/source/api/common_types.rst, doc/source/api/index.rst, pyproject.toml, src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/types/common_types.py, tests/test_parts.py
=> New api: exportNetList()

src/ansys/sherlock/core/parts.py
Checklist:
- [na] Bench test new/modified APIs by using and modifying the code in the example for the API method
- [na] Add new classes to rst files, located at: <pysherlock>\doc\source\api
- [na] Generate documentation
- [na] Verify the HTML. It gets generated at: <pysherlock>\doc\build\html.
- [na] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> parts.py: re-add import

doc/source/api/project_types.rst, pyproject.toml, src/ansys/sherlock/core/project.py, src/ansys/sherlock/core/types/project_types.py, tests/test_project.py
=> Update api addStrainMap()

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/layer.py, tests/test_layer.py
=> New API: delete_all_mount_points()

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/layer.py, tests/test_layer.py
=> New API: update_test_points_by_file()

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/layer.py, tests/test_layer.py
=> New API: export_all_test_fixtures()

tests/test_layer.py
=> export_all_test_points(): Fix test error

src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/layer.py, tests/test_layer.py
=> New API: copy_modeling_region()

src/ansys/sherlock/core/lifecycle.py
Checklist:
- [] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC
=> Bug fix: error message missing

AUTHORS.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, CONTRIBUTORS.md
=> MAINT: add files related to authors, contributions and code of conduction

.github/workflows/ci_cd.yml
=> MAINT: add inputs to ci/cd actions

.github/workflows/ci_cd.yml, .github/workflows/label.yml, doc/changelog.d/426.documentation.md, doc/changelog.d/changelog_template.jinja, doc/source/changelog.rst, doc/source/conf.py, doc/source/index.rst, pyproject.toml
=> MAINT: add action changelog and changelog.rst for release notes

AUTHORS, doc/changelog.d/438.fixed.md
=> fix: proper AUTHORS file

PULL_REQUEST_TEMPLATE.md, doc/changelog.d/446.documentation.md
=> docs: update the pull request template

doc/changelog.d/441.documentation.md, doc/source/api/layer_types.rst, pyproject.toml, src/ansys/sherlock/core/layer.py, src/ansys/sherlock/core/types/common_types.py, src/ansys/sherlock/core/types/layer_types.py, tests/test_layer.py
=> feat: Keith/potting region update

doc/changelog.d/448.documentation.md, doc/source/api/layer_types.rst, src/ansys/sherlock/core/layer.py, src/ansys/sherlock/core/types/layer_types.py, src/ansys/sherlock/core/utils/version_check.py, tests/test_layer.py
Added copy and delete potting region. Fixed issue with require_version decorator for Sphinx documentation.
**Please mention the issue number or describe the problem this pull request addresses.**
=> feat:Keith/copy delete potting region

doc/changelog.d/470.fixed.md, src/ansys/sherlock/core/model.py
Fixing broken import statements after #454
=> fix: import statements

doc/changelog.d/505.added.md, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/types/parts_types.py, tests/test_parts.py
New API: update_pad_properties()
#498
=> feat: new API update_pad_properties()

doc/changelog.d/502.added.md, doc/source/api/parts_types.rst, src/ansys/sherlock/core/errors.py, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/types/parts_types.py, tests/test_parts.py
Implement get_parts_list_properties()
#406 
=> feat: add Parts.get_parts_list_properties()

doc/changelog.d/526.added.md, pyproject.toml, src/ansys/sherlock/core/parts.py, src/ansys/sherlock/core/types/parts_types.py, tests/test_parts.py
new API deletePartsFromPartsList()
#407 
=> feat: new API deletePartsFromPartsList()

doc/changelog.d/530.added.md, pyproject.toml, src/ansys/sherlock/core/project.py, src/ansys/sherlock/core/types/project_types.py, tests/test_project.py
Update IcepakFile options to take in account the new parameters: temperatureOffset and temperatureOffsetUnits
#528 
=> feat: Update thermal maps APIs
