ansys/pysherlock

doc/source/api/analysis.rst
src/ansys/sherlock/core/analysis.py
src/ansys/sherlock/core/errors.py
tests/test_analysis.py

Checklist:
- [] Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)
- [] Check that test code coverage is at least 80% when Sherlock is running and can be connected to using gRPC

Added get_ict_analysis_input_fields and update_ict_analysis_props

---

doc/source/user_guide/index.rst
src/ansys/sherlock/core/lifecycle.py
src/ansys/sherlock/core/parts.py

Feedbacks from Pouya
Checklist:
N/A Check and fix style errors
N/A Bench test new/modified APIs by using and modifying the code in the example for the API method
N/A Add new methods to rst file for updated API script(<pysherlock>\doc\source\api)

Updating API documentation

---

doc/source/api/parts_types.rst
src/ansys/sherlock/core/types/parts_types.py
tests/test_parts.py
tests/test_project.py

Update parts list from AVL: fix unit tests, include classes for enums in API docs.
List thermal maps: fix unit test failure that happens when connected to Sherlock.
Checklist:
- [na] Bench test new/modified APIs by using and modifying the code in the example for the API method

Update parts list from AVL: fix unit tests, include classes for enums in API docs

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/project.py
tests/test_project.py

Checklist:
- n/a Add new classes to rst files, located at: <pysherlock>\doc\source\api

New API: importProjectZipArchive()

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/parts.py
tests/test_parts.py

Checklist:
- n/a Add new classes to rst files, located at: <pysherlock>\doc\source\api

New api: updatePartsListProperties()

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/project.py
tests/test_project.py

Checklist:
- [n/a] Add new classes to rst files, located at: <pysherlock>\doc\source\api

Added export project method and unit tests

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/layer.py
tests/test_layer.py

New API: delete_all_ict_fixtures()

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/layer.py
tests/test_layer.py

New API: delete_all_test_points()

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/layer.py
tests/test_layer.py

New API: update_test_fixtures_by_file()

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/layer.py
tests/test_layer.py

New API: export_all_test_points()

---

doc/source/user_guide/index.rst
pyproject.toml
src/ansys/sherlock/core/analysis.py
src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/parts.py
src/ansys/sherlock/core/types/parts_types.py
tests/test_analysis.py
tests/test_layer.py
tests/test_lifecycle.py
tests/test_model.py
tests/test_parts.py
tests/test_project.py

This includes changes to unrelated code for code consistency and a missing unit test.
Checklist:
- [na] Add new classes to rst files, located at: <pysherlock>\doc\source\api

Update parts list validation props

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/project.py
tests/test_project.py

Create CCA from modeling region API functionality added (with tests)

---

src/ansys/sherlock/core/launcher.py

Update launcher for linux

---

pyproject.toml

@ansnfernand - would it be possible to do a new patch release (0.7.1) once this PR is merged? Even though you made the protobuf version more flexible in the API package, it is also required to make it more flexible on this repo.
Checklist:
- [] Check that test code coverage is at least 80% when …

fix: allow newer protobuf versions

---

pyproject.toml
src/ansys/sherlock/core/analysis.py
src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/parts.py
tests/test_analysis.py
tests/test_layer.py

Also fixed layer unit tests that fail when connected to Sherlock.
Checklist:

Get part validation analysis properties

---

src/ansys/sherlock/core/errors.py
src/ansys/sherlock/core/layer.py
tests/test_layer.py

New api: delete_modeling_region()

---

tests/test_analysis.py
tests/test_parts.py
tests/test_stackup.py

Remove sleep() calls from unit tests since they are no longer needed

---

src/ansys/sherlock/core/launcher.py

Bug fix: single_project_path argument

---

doc/changelog.d/431.added.md
src/ansys/sherlock/core/launcher.py
tests/test_launcher.py

feat: launching a specific version of Sherlock

---

doc/changelog.d/467.fixed.md
doc/source/conf.py

The version in the GitHub link was wrong.

fix: conf.py issue

---

doc/changelog.d/478.added.md
doc/source/api/analysis_types.rst
pyproject.toml
src/ansys/sherlock/core/analysis.py
src/ansys/sherlock/core/types/analysis_types.py
tests/test_analysis.py

Add Analysis.update_component_failure_mechanism_analysis_props()
#475 

feat: add Analysis.update_component_failure_mechanism_analysis_props()

---

.github/workflows/ci_cd.yml
doc/changelog.d/481.dependencies.md
doc/changelog.d/481.documentation.md
pyproject.toml
tox.ini

Add support for Python 3.13. Remove some references to Python 3.8 and 3.9
#460
- [] Make sure that the title of the pull request follows …

MAINT: Add support for Python 3.13

---

doc/changelog.d/488.added.md
src/ansys/sherlock/core/analysis.py
src/ansys/sherlock/core/types/analysis_types.py
tests/test_analysis.py

New API update_semiconductor_wearout_props()
#484

feat: New API update_semiconductor_wearout_props()

---

doc/changelog.d/506.fixed.md
src/ansys/sherlock/core/types/analysis_types.py

Fix this error:
G:\agent\_work\20\PySherlock\src\ansys\sherlock\core\types\analysis_types.py:301: TypeError: 'SUPPLIER' has type str, but expected one of: int

fix: API updatePTHFatigueProps()

---

doc/changelog.d/515.fixed.md
src/ansys/sherlock/core/types/parts_types.py

PartLocation variable was renamed by mistake
#505 

fix: PartLocation variable was renamed by mistake

---

doc/changelog.d/522.fixed.md
src/ansys/sherlock/core/parts.py
src/ansys/sherlock/core/types/parts_types.py
tests/test_parts.py

fix: update_pad_properties - returnCode management

---

doc/changelog.d/535.documentation.md
doc/source/conf.py
pyproject.toml

Modified conf.py and pyproject.toml: in the extensions section, renamed "sphinx_design" to "sphinx-design"
- [] Make sure that the title of …

maint: set sphinx-design as documentation requirement

---

doc/changelog.d/581.documentation.md
doc/changelog.d/581.miscellaneous.md
doc/source/getting_started/installation.rst
src/ansys/sherlock/core/types/common_types.py
src/ansys/sherlock/core/types/layer_types.py
src/ansys/sherlock/core/types/parts_types.py

Fix documentation warnings- change word in installation instructions, capitalize first word of doc comments for type class members.
**Please mention the issue number or describe the problem this pull request addresses.**

docs: fix documentation warnings

---

doc/changelog.d/624.miscellaneous.md
src/ansys/sherlock/core/layer.py
src/ansys/sherlock/core/types/layer_types.py
tests/test_layer.py
tests/test_utils.py

**Please provide a brief description of the changes made in this pull request.**
**Please mention the issue number or describe the problem this pull request addresses.**
- [] Check that test code coverage is at least …

Updated test assertion and test point enums to fix failing unit tests

---

.github/workflows/ci_cd.yml

0.6 release: ci_cd.yml- remove "docs-style" dependency since "docs-style" is no longer defined

0.6 release: ci_cd.yml- remove "docs-style" dependency since "docs-style" is no longer defined
